version: '3'

services:

  logstash-master-movie:
    build: logstash-master-movie/
    environment:
      DATABASE_HOST: "db"
      DATABASE_PASSWORD: "1234"
      DATABASE_PORT: "3306"
      DATABASE_USE_SSL: "false"
      DATABASE_USERNAME: "movielens"
      DATABASE: "movielens"
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
      ELASTICSEARCH_INDEX: "master-movie"
      ELASTICSEARCH_TYPE: "movies"
      PIPELINE_WORKERS: 1
      XPACK_MONITORING_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - db

  logstash-event-tags:
    build: logstash-event-tag/
    environment:
      DATABASE_HOST: "db"
      DATABASE_PASSWORD: "1234"
      DATABASE_PORT: "3306"
      DATABASE_USE_SSL: "false"
      DATABASE_USERNAME: "movielens"
      DATABASE: "movielens"
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
      ELASTICSEARCH_INDEX: "event-tag-%{+YYYY}"
      ELASTICSEARCH_TYPE: "tags"
      PIPELINE_WORKERS: 1
      XPACK_MONITORING_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - db

  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "movielens"
      MYSQL_USER: "movielens"
      MYSQL_PASSWORD: "1234"
      MYSQL_HOST: ""
    volumes:
      - ./mysql/init.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - elk

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.4.3"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=inquiry-cluster
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
      - xpack.monitoring.history.duration=1d
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
    networks:
      - elk

  kibana:
    image: "docker.elastic.co/kibana/kibana:5.4.3"
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_NAME: "kibana"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      XPACK_SECURITY_ENABLED: "false"
      XPACK_MONITORING_ENABLED: "false"
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
